server:
  port: 8082

spring:
  jpa:
    database: h2
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true


  batch:
    jdbc:
      initialize-schema: never
      platform: h2

    job.enabled: false

  # Database
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: test

  jobs:
    jobCsv:
      filename: classpath:test.csv

