apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
  name: demo
  annotations:
    fluxcd.io/ignore: "true"
    fluxcd.io/automated: "false"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - image: docker.io/ayoubmouak/demo:0.0.1-SNAPSHOT # {"$imagepolicy": "default:nginxhello"}
          name: demo
          ports:
            - containerPort: 8083
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          livenessProbe:
            initialDelaySeconds: 2
            periodSeconds: 2
            httpGet:
              port: 80
              path: /healthz/live
          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 2
            httpGet:
              port: 80
              path: /healthz/ready
