


---


apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
  name: demo
  annotations:
    fluxcd.io/ignore: "true"
    fluxcd.io/automated: "false"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - image: docker.io/ayoubmouak/demo:{{.Values.deployment.image.version}} # {"$imagepolicy": "default:demo"}
          name: demo
          ports:
            - containerPort: 8082
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName