version: "3"
services:
  database:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    volumes:
      - ~/postgres/scripts/:/docker-entrypoint-initdb.d/:ro